{
 "title": "System Monitoring",
 "tags": [ "alerts" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "device", "query": { "query": "label_values(device)" } },
   { "name": "interface", "query": { "query": "label_values(interface)" } },
   {
    "name": "cpu_physical_index",
    "query": {
     "query": "label_values(cpu_physical_index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device reachability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_uptime{device=\"$device\"}",
       "legendFormat": "uptime"
      }
     ]
    },
    {
     "title": "Ping reachability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ping_result_code{device=\"$device\"}"
      }
     ]
    },
    {
     "title": "SNMP reachability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(snmp_uptime{device=\"$device\"}) or vector(0)",
       "legendFormat": "status"
      }
     ]
    },
    {
     "title": "SSH reachability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "net_response_result_code{device=\"$device\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Device Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status for $interface",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 35 },
     "repeat": "interface",
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "interface_admin_status{device=\"$device\", interface=\"$interface\"}",
       "legendFormat": "ADMIN"
      },
      {
       "expr": "interface_oper_status{device=\"$device\", interface=\"$interface\"}",
       "legendFormat": "OPER"
      }
     ]
    }
   ]
  },
  {
   "title": "Device Errors and Discards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "repeat": "interface",
     "targets": [
      {
       "expr": "rate(interface_in_error_packets{device=\"$device\", interface=\"$interface\"}[5m])",
       "legendFormat": "IN Errors packets/sec"
      },
      {
       "expr": "rate(interface_out_error_packets{device=\"$device\", interface=\"$interface\"}[5m])",
       "legendFormat": "OUT Errors packets/sec"
      }
     ]
    },
    {
     "title": "$interface Discards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "repeat": "interface",
     "targets": [
      {
       "expr": "rate(interface_in_discards{device=\"$device\", interface=\"$interface\"}[5m])",
       "legendFormat": "IN Discards packets/sec"
      },
      {
       "expr": "rate(interface_out_discards{device=\"$device\", interface=\"$interface\"}[5m])",
       "legendFormat": "OUT Discards packets/sec"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU State - $cpu_physical_index",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 20 },
     "repeat": "cpu_physical_index",
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cpu_state{device=\"$device\",cpu_physical_index=\"$cpu_physical_index\"}",
       "legendFormat": "{{description}}"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 4, "y": 20 },
     "targets": [
      {
       "expr": "cpu_load{device=\"$device\"}",
       "legendFormat": "{{description}}"
      }
     ]
    },
    {
     "title": "CPU Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 20 },
     "targets": [
      {
       "expr": "cpu_errors{device=\"$device\"}",
       "legendFormat": "{{description}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory and Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "storage_used{device=\"$device\"}",
       "legendFormat": "{{description}} | Physical Index {{ storage_physical_index }} | KBytes"
      }
     ]
    },
    {
     "title": "SIze",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "storage_size{device=\"$device\"}",
       "legendFormat": "{{description}} | Physical Index {{ storage_physical_index }} | KBytes"
      }
     ]
    }
   ]
  }
 ]
}