---
version: "3.7"
services:
  telegraf:
    image: telegraf:1.27.1
    restart: always
    container_name: telegraf
    hostname: telegraf
    networks:
      - automation_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./telegraf/mibs/:/usr/share/snmp/mibs/
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - 9126:9126
    command: telegraf --config /etc/telegraf/telegraf.conf
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    hostname: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - automation_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:9.5.6
    container_name: grafana
    hostname: grafana
    networks:
      - automation_net
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring

networks:
  automation_net:
    external: true

volumes:
  grafana_data: {}
