---
groups:
  - name: device_down
    rules:
      - alert: device_net_response_down
        expr: net_response_result_code{job="telegraf", result_type!="success"} != 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Device {{$labels.device}} not reachable through Telegraf net_response for more than 10 seconds"
  
  - name: interface_down
    rules:
      - alert: interface_down
        expr: interface_oper_status==2 and interface_admin_status==1
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Interface {{$labels.interface}} oper state down for more than 10 seconds. Device {{$labels.device}}"
